### ISSUE TITLE
Desplegable de navegación

### ISSUE THREAD

**Issue by LuCostas** [gcba/Obelisco#176]
Nombre en Obelisco: Desplegable de navegación
Tipo de componente: Molécula
Ejemplo en bootstrap:
Ejemplo de aplicación en BA: 
Requerimiento: generar un desplegable que pueda ser utilizado de manera independiente o que esté presente dentro del header. Tiene como fin que el usuario pueda navegar un sitio.

**Comment by JuaneRambosio** [comment]
✏ [Brunch creada](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/uXzLUu46Nr6HrXFUSLTxPB/UI-KIT---Obelisco?type=design&node-id=11970%3A29458&mode=design&t=TtYBkp6XGeuhd7Nm-1)

**Comment by marusaad** [comment]
Luego de realizar el análisis, con @JuaneRambosio comenzamos a construir el componente "Opción de navegación", que son los tipos de opciones (y sus estados) que van a aparecer dentro del desplegable de navegación. 

Las opciones cuentan con:
- Variante de dispositivo (desktop y mobile)
- Variante de tipo (predeterminado, de peligro y en cascada -este último a chequear técnicamente-) 
- Variante de borde (con borde y sin borde)
- Variante de estado (predeterminado, sobre, en foco y deshabilitado. La cascada tendrá un estado adicional de "seleccionado")
- Alineación (predeterminada y a la derecha)
- Propiedad booleana para mostrar ícono a la derecha
- Propiedad booleana para mostrar ícono a la izquierda
- Propiedad booleana para mostrar notificación en el texto

En cuanto a la cascada, estamos teniendo problemas a nivel técnico. El lunes en la daily llevamos la problemática para ver opciones de solución. @camilembo @LuCostas 

![image](https://github.com/gcba/Obelisco/assets/136834096/d14348fa-a889-478c-956f-021889cde6ab)

> ![image](https://github.com/gcba/Obelisco/assets/136834096/3f9f6534-4a09-4cea-859e-0517d2ccd319)

![image](https://github.com/gcba/Obelisco/assets/136834096/1dfbddcb-4ba1-43da-a61d-3093eb8a53bf)

**Comment by marusaad** [comment]
Con @JuaneRambosio finalizamos el análisis y en función de eso comenzamos la construcción del componente y todas sus variantes. 

El análisis ya se encuentra en la page [Desplegables de navegación](https://www.figma.com/file/mqy6dUBWeK47l1CMIYCdkX/An%C3%A1lisis-de-componentes?type=design&node-id=429-4922&mode=design) del archivo Análisis de componentes. 

En la branch de [Desplegables de navegación](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/uXzLUu46Nr6HrXFUSLTxPB/UI-KIT---Obelisco?type=design&node-id=11970%3A29458&mode=design&t=hiyebRJKVrFW3MOb-1) ya se encuentra el componente construido listo para su validación. @camilembo 

![image](https://github.com/gcba/Obelisco/assets/136834096/457b115e-45ec-4ba7-be64-71e0f70e5c16)

**Comment by JuaneRambosio** [comment]
✅ Chevron del Dropdown invertido cuando está activo, hecho!

Avanzamos con la ficha 🤙

**Comment by marusaad** [comment]
🌼 Con @JuaneRambosio finalizamos con los ajustes necesarios del componente "Desplegable de navegación" y finalizamos la ficha. 

📝 **Anotaciones sobre el componente**
- **Se eliminó la elipse de notificación** de las opciones para poder construir **opciones con texto de más de una línea** teniendo en cuenta el uso de las mismas en las páginas de área, que cuentan con nombres de secretarías y otros organismos gubernamentales que pueden ser largos. 
- El botón disparador del deplegable viene de forma predeterminada con el texto "Desplegable" y el chevron hacia abajo. Depende del lado del que se desplieguen las opciones, el chevron aparecerá a la izquierda o a la derecha del texto. La propiedad de mostrar ícono permanece en false por default y se puede activar a gusto del diseñador. 
- Se le colocó el texto "Cerrar sesión" y el ícono correspondiente a la opción de peligro, para reforzar la razón de su uso. 
- **Se cambió la tipografía** del botón disparador a un h5 de Mobile (se encontraba en desktop)
- Al desplegarse, **el botón disparador quedará en estado activo**. Y se sumó el estado de foco a las variantes del mismo. 

🗄 **Ficha**
- Se decidió organizar las fichas de la siguiente manera: dentro de la navegación horizontal, habrá dos fichas (a nivel 3 de navegación) sobre desplegables. Una de desplegables de selección (para filtros y formularios) y otra ficha de desplegables de navegación. 
- Se completaron buenas y malas prácticas

![image](https://github.com/gcba/Obelisco/assets/136834096/0a9d77a6-c164-4025-9d39-596a0cac0957)


🕒 **Pendientes para más adelante**
- En la ficha de "Navegación y pestañas" deberá incorporarse la información de cómo se organizan los desplegables y botones en mobile (de forma vertical) 
- En la ficha de "Navegación y pestañas" incorporar un enlace a la ficha de desplegables de navegación para profundizar sobre el componente como molécula. 
- En la ficha de "Encabezado de página" incorporar un enlace a la ficha de desplegables de navegación para profundidad sobre el componente como molécula. 

@camilembo el componente y la ficha quedan disponibles para su revisión. 

![image](https://github.com/gcba/Obelisco/assets/136834096/27aed19b-b681-41aa-b9a5-358e16dedca9)
![Desplegable de navegación](https://github.com/gcba/Obelisco/assets/136834096/5a1eb34a-7b30-4933-91bf-05777648c68e)
![Desplegables de navegación](https://github.com/gcba/Obelisco/assets/136834096/d7a0e47b-d03f-47b1-9cf7-d1f607c6aa7b)

**Comment by camilembo** [comment]
Tengo un par de dudillas:
1- Este punto debería llevarme a desplegables de selección no? no solo desplegables


![Image](https://github.com/gcba/Obelisco/assets/137331016/06e9cd3b-622f-4458-8487-2fc68225b903)


2- Acá habría que aclarar que es en mobile la disposición vertical? porque en desktop si podríamos usar un desplegable al lado del otro siempre y cuando ocupen hasta 8 columnas 


![Image](https://github.com/gcba/Obelisco/assets/137331016/6860954d-2f5b-4923-92d2-d9cb13e48df0)


3- A qué le llaman acciones destructivas? por ejemplo si apareciera una acción de eliminar sería? 🤔 


![Image](https://github.com/gcba/Obelisco/assets/137331016/70976082-e3e6-466a-93d9-75a9d7463e1e)

Eso es todo! ❤

**Comment by camilembo** [comment]
Buenísimo!! lo entregamos hoy en la weekly con desarrollo 💪

**Comment by marusaad** [comment]
Elaboramos unos frames dentro de la branch del componente a modo de handoff con especificaciones del comportamiento de las opciones y desplegables de navegación. También incluimos una demo con el componente animado. 

![Handoff - Opciones de navegación](https://github.com/gcba/Obelisco/assets/136834096/f12638b8-dfb6-47eb-a094-66bec4a55ade)

![Handoff - Desplegables de navegación](https://github.com/gcba/Obelisco/assets/136834096/fc45ce39-4414-4693-9c83-e8da9690b93d)

**Comment by marusaad** [comment]
**Se eliminaron todas las opciones de navegación que tenían borde** porque no convivían con la caja contenedora de opciones del desplegable. Sólo quedan con borde los estados "sobre" y "en foco"

Se corrigió la branch @camilembo . 
La ficha no tenía ejemplos de opciones de navegación con bordes por lo que no deben realizarse cambios. 




![Image](https://github.com/gcba/Obelisco/assets/136834096/0f332833-709e-4d7d-972a-9ea012c02b60)

**Comment by camilembo** [comment]
Se hizo merge el día 07/09
