### ISSUE TITLE
Listas - Lista Informativa

### ISSUE THREAD

**Issue by LuCostas** [gcba/Obelisco#177]
Nombre en Obelisco: Lista informativa
Tipo de componente: Molécula
Ejemplo en bootstrap: 
Ejemplo de aplicación en BA: https://buenosaires.gob.ar/tramites/consulta-de-usos
Requerimiento: Construir componente de lista informativa (molécula) y una lista de ítems con subtítulo (organismo)
- Dispositivos: desktop y mobile
- Variantes: con check para requisitos y con bullet para información / con título y sin título para la lista como organismo.

**Comment by marusaad** [comment]
Se creó una branch de [Lista informativa](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/C30D8HpS0MlPvLe5ZoBxCP/UI-KIT---Obelisco?type=design&node-id=1333%3A14738&mode=design&t=MvtcLkIIDvq7FVxo-1) y se trabajará dentro de la page "Listas"

**Comment by marusaad** [comment]
🆕 Se comenzó a trabajar sobre el análisis e investigación del componente "Lista informativa"

Como punto de partida se tomaron los siguientes requisitos:

**Dispositivos**
- Mobile (2 col)
- Desktop (8 col máximo)

**Variantes molécula (ítem)**
- Con check (para requisitos)
- Con bullet (para otra información o recordatorios)

**Variantes organismo (lista de ítems)**
- Con subtítulo
- Sin subtítulo 

🔍 Se mapearon casos en otros DS y se buscaron casos de uso actuales en la página de buenos aires

![Referencias de otros DS + artículos](https://github.com/gcba/Obelisco/assets/136834096/c1162a1d-e267-4c76-9163-cdc7d540d8ae)
![Casos de uso actuales](https://github.com/gcba/Obelisco/assets/136834096/8b8f46b1-9060-43e0-9b20-6838a5b2a9c9)


🧐 Temas para pensar a partir del análisis y ver el lunes en la daily: 
- ¿Cuáles son las razones que existen para que el check de requisitos haya pasado del color activo a ser del mismo color del texto? ¿Sería relevante que tenga, por ejemplo, un color con una función semántica como el verde? 
- ¿Sería relevante que exista, así como un check, un ícono de un requisito no necesario? (Ej. como utilizamos en las fichas de los componentes con buenas y malas prácticas) 
- Dentro de la page de "Trámites" que tiene diferentes tipos de componentes, existe uno denominado "lista_punto_informacion". ¿Sería relevante crear una variante para estos casos? Entendiendo que no podría incorporarse a un organismo, sino que sería un ítem informativo individual. 

![lista_punto_informacion](https://github.com/gcba/Obelisco/assets/136834096/8fcc2792-d810-480d-b352-6a2c5292ff9d)

**Comment by marusaad** [comment]
👉 Se avanzó con la construcción del componente de "lista informativa" 

**Ítem de lista (molécula de ícono+texto)**

- Dispositivo (desktop 8 col y mobile 2 col) 
- Tipo ("de información" con bullet, "de requisito" con check) // queda en duda la nomenclatura, tal vez es mejor poner "con viñeta" y "con check" porque la lista es siempre informativa. 

**Lista informativa (organismo de ítems+subtítulo)**

- Dispositivo (desktop 8 col y mobile 2 col)
- Tipo ("de información" con ítems con bullet, "de requisitos" con ítems con check) // decidí que sean 2 variantes para que no se mezclen los usos (o sea que alguien en la lista de requisitos incorpore un ítem con bullet) 
- Mostrar subtítulo (propiedad booleana)

![image](https://github.com/gcba/Obelisco/assets/136834096/aa5f9f63-a5d6-49f8-a72a-3ee2e60dfb61)
![image](https://github.com/gcba/Obelisco/assets/136834096/d39ce9cc-7720-4908-8673-c0630d6f919b)

📌 Como conversamos en la daily, la opción de que el contenido pueda tener un enlace se va a mostrar en la ficha como un ejemplo de uso, pero no se incorpora al componente. 

Queda a chequear por @camilembo y se puede comenzar con la ficha 

![Listas-Lista informativa](https://github.com/gcba/Obelisco/assets/136834096/d60800e7-6111-4b75-985b-11090adc7739)

**Comment by camilembo** [comment]
Maruuu, coincido con la nomenclatura "con viñeta" y "con check"

**Comment by marusaad** [comment]
🎯 Se avanzó con el armado de la ficha del componente de "Lista informativa" 

💭 **Observaciones**
- Me queda la duda de si nomenclar los organismos a partir de los íconos que tienen los ítems. Es decir, quedaría por un lado "Lista con viñetas" y por el otro "Lista con checks". Considero que está bueno nomenclar a partir del uso a la lista, por ejemplo "Lista de requisitos" a la que tiene check, pero habría que ver en el caso de la lista con viñetas (podría ser "Lista general" o "lista desordenada" o "lista predeterminada")
- En rojo dejé un texto de las malas prácticas que me queda en duda. Estaría bueno una vez que tengamos una bajada de contenidos con respecto a cómo estructurar los requisitos la podamos linkear a la ficha. Por ahora lo dejé en rojo porque creo que no es el momento. 

Adjunto la ficha para ir chequeando contenidos @camilembo 

![Lista de pasos](https://github.com/gcba/Obelisco/assets/136834096/46ff4edd-43d5-4046-a68b-a6c7f354041a)

**Comment by camilembo** [comment]
Se hizo **merge** el día 21/09/2023

**Comment by marusaad** [comment]
- Se incorporaron instancias de texto para los títulos del paso y sus descripciones dentro del UI Kit.
- Se incorporó descripción del componente y link a documentación



![Image](https://github.com/gcba/Obelisco/assets/136834096/90e35dea-86b6-4e5d-b8c0-f1a522171062)

@camilembo con esto ya se puede pasar a completado

**Comment by camilembo** [comment]
Gracias Maru!
Merge de estos ajustes hecho el 29/09 :)
