### ISSUE TITLE
Barra de desplazamiento (scrollbar)

### ISSUE THREAD

**Issue by Diehault** [gcba/Obelisco#222]
**Nombre en Obelisco:** barra de desplazamiento.
**Tipo de componente:** átomo.
**Necesidad solicitada por:** Diseño.

### Requerimiento

Actualizar el componente en el UI Kit (construcción del componente y plantilla).
Unificar la barra de desplazamiento que aparece en Storybook con la que está en el UI Kit.

**Comment by Diehault** [comment]
¡Hola! 🤠​

Actualizamos el componente en el UI Kit siguiendo el requerimiento, y empatamos el diseño con lo que teníamos en desarrollo dentro de Storybook.

La barra de navegación es un átomo que no tendría ficha y que, actualmente, no está en Storybook como componente. Podría sumarse si lo ven necesario.

### ¿Qué hicimos?

- Reconstruimos el componente desde 0, armándolo nuevamente en el UI Kit.
- Actualizamos la plantilla del componente en el UI Kit.

### ¿Cómo se ve ahora?

![Image](https://github.com/gcba/Obelisco/assets/144037453/3c40a7d7-7f16-45f2-97f7-0449f8528fed)

Dejo por acá el [link a la branch](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/tQHMPYzGFFiB8Bs45oHiuZ/UI-KIT---Obelisco?type=design&node-id=957%3A8809&mode=design&t=02y2femFv7zekqOo-1) donde se encuentra ahora mismo.

**Comment by camilembo** [comment]
Se hace merge en el UI Kit para poder construir la tabla de forma completa
**02/02/2024**
