### ISSUE TITLE
Falla al compilar integrado en un proyecto de angular

### ISSUE THREAD

**Issue by CintiaCapece** [gcba/Obelisco#45]
**Error**
Al momento de levantar un proyecto de Angular(version 13.0), no compila porque falla en la compilacion de algunos componentes: entre ellos  "Breadcrumb" y "Pagination". El error es el siguiente:

![image](https://user-images.githubusercontent.com/13827090/150996657-feb1bc2b-60d2-46c5-9dac-1f6578aecaf3.png)

**Cómo reproducirlo**
Pasos para reproducir el comportamiento:

1. En la carpeta raíz del proyecto angular, ejecutar `npm start`

Observación: Obelisco esta integrado como dependencia en el package.json del proyecto.

Versiones de las dependencias en Package.json:

{
  "name": "portal-ciudad",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve ",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/localize": "^13.1.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@fortawesome/angular-fontawesome": "^0.10.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@gcba/obelisco": "^1.18.2",
    "bootstrap": "^4.5.0",
    "codelyzer": "^6.0.2",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.3",
    "@angular/cli": "~13.0.3",
    "@angular/compiler-cli": "~13.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "css-loader": "^3.5.3",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "node-sass": "^4.14.1",
    "resolve-url-loader": "^4.0.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.4.3"
  }
}

**Tecnología**

 - Dispositivo: Se probo en varias computadoras 
 - Sistema operativo: Windows10 y Ubuntu 20
 - Navegador: Chrome y Firefox

**Comment by nirougi** [comment]
Hola @CintiaCapece, en la versión 1.21.1 subimos un arreglo que debería resolverlo.
¿Podrás probar actualizando para confirmar que con esto ya les funciona en esa implementación?

Muchas gracias.

**Comment by CintiaCapece** [comment]
Hola @nirougi , actualicé la versión para probar pero sigue fallando en lo siguiente: 

![image](https://user-images.githubusercontent.com/13827090/151434835-df2faac9-5484-4556-bfa2-071d3a668a41.png)

Gracias a ustedes por el seguimiento!

**Comment by nirougi** [comment]
@CintiaCapece Bueno, bien que avanzamos del error anterior.
Analizando este, el problema pareciera ser que al `postcss-loader` que están usando no le gusta uno de los SVG que tenemos incrustados.

Probé recién de instalar ese mismo loader en Obelisco en mi máquina local y no me tiró ningún error 🤔 
¿Podrás pasarme la configuración que tienen en webpack de ese loader y la versión que están usando?
Mismo me parece raro que ese paquete no esté en la configuración que compartiste en el primer mensaje.

Por último, ¿podrás probar sacando ese loader y ver si hay algún otro error o con eso ya quedaría?

**Comment by CintiaCapece** [comment]
@nirougi   La versión es "postcss-loader": "^6.2.1", no tenemos en el proyecto incorporado webpack aunque existe el angular.json que tiene las siguientes configuraciones:

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "portal-ciudad": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/portal-ciudad",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/assets/styles/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "options": {
            "port": 4200,
            "host": "0.0.0.0"
        },
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "portal-ciudad:build:production"
            },
            "development": {
              "browserTarget": "portal-ciudad:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "portal-ciudad:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/assets/styles/styles.scss"
            ],
            "scripts": []
          }
        }
      }
    }
  },
  "defaultProject": "portal-ciudad"
}

Pd: si bien entiendo Obelisco está realizado en React y este es un proyecto Angular.

--------------------------------------------------------------------------------------------------------------------------------------------

Para eliminar el loader  (postcss-loader), realice dos pruebas:

1.  Lo removí del package.json, eliminé el node_modules , reinstalé las dependencias del package.json y levanté el proyecto. Sigue lanzando los dos errores que anteriores ( el del loader y el de no reconocer la importacion de las variables/colors de obelisco) 

![image](https://user-images.githubusercontent.com/13827090/151640769-09da35d2-55a5-477c-b45c-e635a024d65a.png)

2. Observando la imagen anterior, por mas que haya eliminado el loader del package.json, postcss-loader seguía estando en el node_modules. Entonces, lo elimine de ese directorio también y al momento de levantar el proyecto lanza este error :

![image](https://user-images.githubusercontent.com/13827090/151641474-962dfdd8-61c2-468c-ae0e-11f64b8467b1.png)

Obviamente es asociado a que no lo encuentra, creo que eliminarlo no es una opción viable.

**Comment by nirougi** [comment]
@CintiaCapece  Ok, parece que es una dependencia de Angular entonces.

En principio, el error que te marca por el archivo `variables/colors` que no encuentra parece ser porque lo están llamando mal en su proyecto, específicamente en el archivo `footer-portal/footer-portal.components.scss`.

Respecto a los del `postcss-loader`, la verdad es que me es imposible poder resolverlo sin tener un error más claro de qué lo hace fallar o poder reproducirlo. Intenté configurar ese loader en Obelisco, pero tengo que usar una versión anterior a la que tienen ustedes porque usamos webpack 4, ustedes parece que están usando webpack 5 (como dependencia de angular/cli).

Más allá de eso, hice un cambio de algo que creo podría ser lo que molesta, lo cual no es un error en sí por lo que no sé si va a arreglarlo. Te recomiendo actualizar Obelisco a la versión v1.21.2 y ver si se resuelve.

**Comment by CintiaCapece** [comment]
@nirougi  Hola Nico! Gracias por la respuesta, recien pude ver esto. A priori, actualicé la versión de Obelisco en el proyecto. Se resolvió lo de variables/colors  porque se habia unos imports que estaban demás en ese archivo.

Respecto a lo de postcss-loader , sigue tirando este error: 
![image](https://user-images.githubusercontent.com/13827090/154298428-990fdd56-b28a-4acc-a00f-8163631366e9.png)
Por algun motivo desconocido, no esta compilando el svg del paginado de Obelisco.

**Comment by nirougi** [comment]
@CintiaCapece Ahí volví a subir otro cambio para ver si se soluciona con eso, deberían actualizar a la versión `1.22.1`.

Si con eso no lo podemos resolver, voy a necesitar que me den acceso al código o a un ejemplo donde suceda ese mismo error, porque no tengo forma de probar los cambios y publicar versiones nuevas para ver qué pasa es insostenible.

Quedo atento a sus avances, saludos.

**Comment by CintiaCapece** [comment]
@nirougi Actualice la versión de Obelisco pero sigue trayendo el mismo error en el sistema. 
Contactaré al equipo por Discord para evaluar posibles soluciones.
Saludos.

**Comment by nirougi** [comment]
Cierro el issue porque está resuelto.
