### ISSUE TITLE
Collapsible Sidebar - Backoffice

### ISSUE THREAD

**Issue by mmorenogcba** [gcba/Obelisco#61]
Buenas tardes, estaríamos necesitando la posibilidad de incorporar una barra lateral desplegable para incluir información en un nuevo desarrollo orientado a backoffice.
Hay componentes de navegación (https://gcba.github.io/Obelisco/?path=/story/componentes-navegaci%C3%B3n--simple) y colapsables (https://gcba.github.io/Obelisco/?path=/story/componentes-colapsable--seleccion-unica), pero no encontramos del tipo sidebar (ej: https://www.cssscript.com/demo/smooth-collapsible-sidebar-navigation/ )

Muchas gracias.
Saludos,

Mariano.

**Comment by mmainero** [comment]
Hola @mmorenogcba, buenas tardes! 
Cómo mencionaste, desde el obelisco el estándar actual que tenemos para la navegación lateral es exactamente ese que pasaste (navegación simple). No tenemos mapeado todavía el comportamiento de colapsar la barra lateral. 
Nuestro proceso de trabajo inicia desde el análisis de la necesidad de ese comportamiento, ¿nos podrían compartir documentación que tengan disponible para así entender mejor el contexto de la decisión? De no poseer nada, les proponemos un meet de 15 minutos con ustedes y el proveedor para así dar mejor respuesta. 

Muchas gracias!

**Comment by mmorenogcba** [comment]
Hola, el primer link creo que se rompió porque actualizaron los componentes, sería este https://gcba.github.io/Obelisco/?path=/story/componentes-navegaci%C3%B3n-vertical--simple, pero la idea es tener un sistema de navegación lateral que se pueda colapsar para ganar más espacio de trabajo. Como te comenté, la idea es implementarlo en un backoffice, pero quizás no quieran agregar ese componente acá si es que esto está más orientado al front del ciudadano y quizás se prefiera iniciar un repo distinto para componentes que se ajusten a este tipo de desarrollos.

Conversamos con el proveedor y tendría disponible el día martes próximo, confirmame por favor disponibilidad y ya lo programamos.

Muchas gracias.
Saludos,

Mariano.

**Comment by sbianchi2022** [comment]
Estimad@s, buen día. Les consulto status de los solicitado. En caso de aun no haberlo realizado, les consulto fecha estimada de resolución, para así poder facilitárle este componente al proveedor del desarrollo en curso.
Aguardo pronta respuesta y gracias. 
Saludos.-
SB
