### ISSUE TITLE
Error en estilo de componente breadcrumb (background-color)  v1.34.2

### ISSUE THREAD

**Issue by adolfojam98** [gcba/Obelisco#85]
**Error en estilo de componente breadcrumb (background-color)**
Se encontro un error en los estilos css, cuando uno quire usar un componente breadcrumb siempre aparece con un background-color  no esperado, revisando estos estilos me di cuenta que ese estilo esta en "none".

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/56196556/182377274-94a7ba76-519e-4065-9674-0cc386add68b.png)

**Versión utilizada: v1.34.2**

**Comment by lautarorodriguez96** [comment]
Hola @adolfojam98 Gracias por la aclaración! Corregimos este fix con una nueva versión.

Saludos.
